# This workflow will install Python dependencies and build the Albayan application using cx-Freeze on Windows.

name: Albayan_beta

on:
  push:
    branches: [ "albayan_beta" ]
  pull_request:
    branches: [ "albayan_beta" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cx-Freeze
        if (Test-Path "requirements.txt") { pip install -r requirements.txt }

    - name: Build with cx-Freeze
      run: |
        python setup.py build

    - name: Archive build output
      uses: actions/upload-artifact@v3
      with:
        name: albayan-beta-cx-freeze-build
        path: build/
